### ISSUE TITLE
POC - Git API 

### ISSUE THREAD

**Issue by eyalFischel** [eyalFischel/maakaf-stats#2]
Investigate the Git API:
1. What information can we get from the REST API?
2. What information can we get from the Graph API?
3. What limitations do we have while using the API?

**Comment by mario99logic** [comment]
In terms of daily information available from the GitHub REST API, we can access the following statistics for repositories that I think is relevant:

- Number of Views: Shows the daily and weekly views count along with unique visitors. 
    https://api.github.com/repos/{owner}/{repo}/traffic/views

- Number of Clones: Provides the count of daily and weekly clones along with unique cloners. 
   https://api.github.com/repos/{owner}/{repo}/traffic/clones

- Number of Contributions: While daily contributions per se aren’t directly available we can track daily commits using
    https://api.github.com/repos/{owner}/{repo}/stats/commit_activity

I've successfully used these endpoints to monitor my repos, I used a personal token for now to try these out.

We cant get information by the hour , only options are daily or weekly.

I will continue investigating for more relevant content, and investigate the limitations. for another specific and relevant data that we need from the api tell me because there are a lot of information we can get

**Comment by eyalFischel** [comment]
First, we can go for the daily stats (it's fine for our case).
Second, we need to collect (in my opinion, feel free to add if needed) the following: (by graphs)

- How many commits and PRs have been created (for each repo) for the following week/day.
- Which users are the most active (PRs, commits, tickets, etc.).
- Which repos are the most active (tickets, comments, commits, PRs).
- Number of stars, forks, watchers, and views for each repo over time.
We can add more information in the future, such as the number of new projects created in the past month.

**Comment by eyalFischel** [comment]
After collecting this information, feel free to create your first Python script to fetch it for a POC. 
**Please do not share your private key with us.**
@mario99logic

**Comment by eyalFischel** [comment]
Ok, great. Please create a branch called "git_api" or "git_collector" and submit it. Let's review it together. 
The next step will be to create the tables in the PostgreSQL database. 
Please read and assist with the following ticket:[https://github.com/eyalFischel/maakaf-stats/issues/9](Design the DB)
