### ISSUE TITLE
Create project management conventions 

### ISSUE THREAD

**Issue by supervxn** [eyalFischel/maakaf-stats#23]
Things to consider: 

- * Are we working in iterations?
- What milestones should we set?
- How are tasks prioritized?
- Board settings: colomns, groups, lables etc.
- How is the task size determined (XS,S,M...)
- Are we setting task durations?

**Comment by supervxn** [comment]
@eyalFischel I think we should create priorities. It's just like another label.

For the Backlog - It's really important data to see which developer takes prioritiesed issues.

**Comment by supervxn** [comment]
Things to concider:
1. Are we working in iterations?
2. What milestones should we set?
3. How are tasks prioritized?
4. Board settings: colomns, groups, lables etc.
5. Are we setting task durations?

**Comment by eyalFischel** [comment]
I will answer each question separately: @supervxn 
>> Are we working in iterations?
Yes.
**Planned** the first version (by basic needs) -> **developing** the first version -> **Testing** the version 
Next step will be **Feedback** (after developing Grafana and Elastic).
After getting the feedback we will go over the steps again for the next version. 

>> What milestones should we set?
If we include only what we haven't finished yet:
1. Developing the first infrastructure (DB and Grafana\elastic)
2. Creating a CI\CD for deployment
3. Deploy the first version while picking env.
4. Developing the First version of the API

>> How are tasks prioritized?
Waterfall:
main priority
1. Data collectors ( collecting data from discord\Git)
2. DB development 
3. Grafana\Elastic Development 
4. CI\CD development 
5. Deployment
6. API development's
lowest priority

>> Board settings: colomns, groups, lables etc.
Didn't understand your question 

>>Are we setting task durations?
No, because we are doing it without caring about how much time it takes for the developers.

**Comment by supervxn** [comment]
I created the milestones,
